### **Description**

The data used in the study was collected from a randomly selected sample of mobile phone users in the six Class 1 metropolises of India— Bengaluru, Chennai, Delhi, Kolkata, Mumbai and Hyderabad. These cities had seen a high number of active cases (22.30% of all cases), and deaths due to COVID-19 (37.99% of all cases), and the shortage of medical facilities. Respondents were residents of the city, aged between 21 and 60 years—randomly selected from a list of mobile telephone users. The survey was undertaken during the months of August and September 2020 (when the lockdown had ended, but COVID cases and deaths were rising rapidly) and then resurveyed again in July-August 2021 (after the second wave had ended). These periods are referred to as T1 and T2, respectively.

The survey was administered using the abridged shorter version of the DASS questionnaire, DASS-21 (Lovibond & Lovibond, 1995). The raw scores were used to create z-scores, which were then recoded into five categories (normal, mild, moderate, severe and extremely severe) following the methodology suggested by Lovibond and Lovibond (1995).

####**DASS-21 (Depression Anxiety Stress Scale – 21 items)** is a widely used psychological assessment tool developed by Peter Lovibond and Sue Lovibond. It is a shortened version of the original 42-item DASS and is designed to measure three related negative emotional states: Depression, Anxiety, and Stress.

The scale consists of 21 self-report items, with 7 items allocated to each subscale. Respondents rate how much each statement applied to them over the past week using a 4-point Likert scale ranging from 0 (“Did not apply to me at all”) to 3 (“Applied to me very much or most of the time”).

Scores for each subscale are calculated by summing the relevant items (and often multiplying by two to maintain comparability with the original DASS-42). Higher scores indicate greater levels of psychological distress. The DASS-21 is widely used in research and clinical settings due to its reliability, validity, and ability to distinguish between symptoms of depression, anxiety, and stress.

###**Motive behind analysis**

As I proceed further I will go through various steps and analyse the data end-to-end to figure out the possible factors of causing mental health detereoriation and will try to gain other insights from it.

In [ ]:
import numpy as np
import pandas as pd
mh = pd.read_csv('/content/adult mental health in indian metro cities 2001-2021 (reformed).csv')

In [ ]:
# Install itables
%pip install itables

Collecting itables
  Downloading itables-2.7.0-py3-none-any.whl.metadata (12 kB)
Downloading itables-2.7.0-py3-none-any.whl (2.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 23.6 MB/s eta 0:00:00
Installing collected packages: itables
Successfully installed itables-2.7.0

In [ ]:
from itables import init_notebook_mode
init_notebook_mode(all_interactive=True)
mh.head()

   slno             name     city  age     sex religion    caste  \
0  5056  SOUMYA DASGUPTA  Kolkata   46    Male    Hindu  General
1  5058        TITAS ROY  Kolkata   28    Male    Hindu  General
2  6036      MANOJ MOGRE   Mumbai   41    Male    Hindu  General
3  3014     Anunay Kumar    Delhi   35    Male    Hindu  General
4  6075      REKHA SAKYA   Mumbai   25  Female    Hindu    SC/ST

        study_level       occupation empl_st_before_lckdwn  ... anxiety T2  \
0        Graduation         advocate         Self-employed  ...         18
1  Above graduation  research analys    Full-time salaried  ...          0
2        Graduation          service    Full-time salaried  ...         16
3        Graduation          service    Full-time salaried  ...          4
4         Secondary          service    Part-time salaried  ...          4

   anxiety_level T2   relative_anx stress T1 stress_level T1 stress T2  \
0            Severe  Deterioration         8          Normal        20
1            Normal           Same        10          Normal         6
2            Severe  Deterioration         2          Normal        12
3            Normal           Same         6          Normal        12
4            Normal       Improved        16            Mild        10

  stress_level T2 relative_stress dass21_raw T1 zdass21 T1
0        Moderate   Deterioration     10.000000  -0.117815
1          Normal            Same      5.333334  -0.577837
2          Normal            Same      6.000000  -0.505113
3          Normal            Same      3.333333  -0.769021
4          Normal        Improved     24.666666   1.328384

[5 rows x 95 columns]

###**Column Descriptions:**

T1 → 1st phase, Aug–Sept 2020 (post-lockdown, rising cases)

T2 → 2nd phase, July–Aug 2021 (post second wave)
####**Identification & Demographics**

* slno – Serial number (unique respondent ID)

* name – Respondent name (if anonymized, coded ID)

* city – Metro city of residence (Bengaluru, Chennai, Delhi, Kolkata, Mumbai, Hyderabad)

* age – Age (21–60 years)

* sex – Gender of respondent

* religion – Religious affiliation

* caste – Social category

* study_level – Highest education level completed

* occupation – Type of occupation

* empl_st_before_lckdwn – Employment status before lockdown

* pymnt_st_main_erng_memb – Payment/salary status of main earning member

####**Household Characteristics**

* family_mems – Total family members

* agd_memb_above60 – Family members aged above 60

* mrd_and_spouse_living_together_or_not – Marital cohabitation status

* residential_pattern – Type of housing arrangement

* owned/rented – Housing ownership status

* change_of_occ – Change in respondent’s occupation

* change_of_occ_mainmember – Change in occupation of main earning member

* married_unmarried – Marital status

* residence_change – Whether residence changed during pandemic

* leisure_time T1/T2 – Change in leisure time

#### **Economic Condition (T1 & T2)**

* family_economicaly_affected T1/T2 – Whether family income was affected

* monthly_expenditure T1/T2 – Total monthly household expenditure

* mpce T1/T2 – Monthly Per Capita Expenditure

* fmpce T1/T2 – Family Monthly Total Expenditure (for more refer below)

* education_of_children T1/T2 – Impact on children’s education

####**COVID & Health Status (T1 & T2)**

* covid_case T1/T2 – Whether respondent had COVID

* fam_mem_suff_hyp-tens/bp/dbts/canc T1/T2 – Family member with chronic illness (hypertension, BP, diabetes, cancer)

####**DASS-21 Symptom Items (T1 & T2)**

Each of these represents one DASS-21 question (0–3 scale):

Examples:

* finding_hard_to_wind_down – Difficulty relaxing

* dry_mouth – Experience of dry mouth

* not_experiencing_+ve_felling – Lack of positive feelings

* breathing_difficulty – Shortness of breath

* difficulty_in_initiative_to_do_things – Low motivation

* felt_downhearted_and_blue – Sadness/depressive mood

* felt_life_is_meaningless – Feeling life lacks meaning

etc.

(All are repeated for T1 and T2.)

####**Mental Health Scores**

* depression T1/T2 – Depression subscale score

* depression_level T1/T2 – Severity category (Normal–Extremely Severe)

* relative_dep – Change in depression between T1 and T2

* anxiety T1/T2 – Anxiety subscale score

* anxiety_level T1/T2 – Anxiety severity category

* relative_anx – Change in anxiety

* stress T1/T2 – Stress subscale score

* stress_level T1/T2 – Stress severity category

* relative_stress – Change in stress

* dass21_raw T1 – Total raw DASS-21 score

* zdass21 T1 – Standardized (z-score) DASS-21 score

####  **Monthly Per Capita Expenditure(MPCE)** → It’s commonly used in Indian surveys like National Sample Survey Office (NSSO).

> MPCE = (Total household monthly consumption expenditure) / (number of household members)

**fmpce:**
#####   fmpce -> the rounded up monthly income figures or Family MPCE are converted into USD which was given the colun name -> fmpce.
The corresponding 1st column -> fmpce T1 represents the gross family income in T1 phase and 2nd column -> fmpce T2 represnts the gross family income in T2 phase.

In [ ]:
mh.head(2)

,slno,name,city,age,sex,religion,caste,study_level,occupation,empl_st_before_lckdwn,...,anxiety T2,anxiety_level T2,relative_anx,stress T1,stress_level T1,stress T2,stress_level T2,relative_stress,dass21_raw T1,zdass21 T1
0,5056,SOUMYA DASGUPTA,Kolkata,46,Male,Hindu,General,Graduation,ADVOCATE,Self-employed,...,18,Severe,Deterioration,8,Normal,20,Moderate,Deterioration,10.000000,-0.117815
1,5058,TITAS ROY,Kolkata,28,Male,Hindu,General,Above graduation,RESEARCH ANALYS,Full-time salaried,...,0,Normal,Same,10,Normal,6,Normal,Same,5.333334,-0.577837

#####
 As I didn't understand what 'zdass21' was, I performed these following tests.

In [ ]:
np.corrcoef(mh['dass21_raw'], mh['zdass21'])

array([[1.        , 0.99999119],
       [0.99999119, 1.        ]])

#####
* As I analysed the correlation value I found it is near 1 but min(zdass21) and max(zdass21) not lying between [-1,1]. So this row is not correaltional coefficient.

In [ ]:
mh['zdass21'].mean()

np.float64(0.031169276149899398)

In [ ]:
mh['zdass21'].std()

0.9763592548840906

#####
* So mean ~ 0 and std ~ 1, this says that column 'zdass21' is  a normalised column of 'dass21_raw'.

In [ ]:
mh.head(2)

,city,name,age,sex,religion,caste,study_level,study_level(specific),occupation,empl_st_before_lckdwn,...,anxiety T2,anxiety_level T2,relative_anx,stress T1,stress_level T1,stress T2,stress_level T2,relative_stress,dass21_raw T1,zdass21 T1
0,Kolkata,SOUMYA DASGUPTA,46,Male,Hindu,General,Graduation,LLB,ADVOCATE,Self-employed,...,18,Severe,Deterioration,8,Normal,20,Moderate,Deterioration,10.000000,-0.117815
1,Kolkata,TITAS ROY,28,Male,Hindu,General,Above graduation,MASTERS,RESEARCH ANALYS,Full-time salaried,...,0,Normal,Same,10,Normal,6,Normal,Same,5.333334,-0.577837

####**Problems with the dataset:**

* In the expenditure columns (monthly_expenditure, fmpce, mpce) there is someone whose all entries are 0. `accuracy`    *dealt*

* There are entries which has (monthly_expenditure, fmpce, mpce)T1 == 0 but T2 != 0 and vice-versa `accuracy`     *dealt*

* There are missing values in 'monthly_expenditure T1/T2', 'fmpce T1/T2', 'mpce T1/T2', 'education_of_children T1/T2'  `completeness` *somewhat handled*

* In the 'occupation' column there are entries in uppercase `consistency` *dealt*

* In the 'name' column there are entries in lowercase `consistency`

* We will work with INR, so we need to make the 'mpce' column into INR currency from USD `accuracy` *dealt*

* There's no dass21 section for T2 phase `feature engineering`

In [ ]:
mh.describe(include='all')

               slno      name       city         age     sex religion  \
count    994.000000       994        994  994.000000     994      994
unique          NaN       914          6         NaN       2        3
top             NaN  Srinivas  Bengaluru         NaN  Female    Hindu
freq            NaN         4        182         NaN     517      902
mean    3541.383300       NaN        NaN   38.149899     NaN      NaN
std     1723.814011       NaN        NaN    9.087394     NaN      NaN
min     1001.000000       NaN        NaN   21.000000     NaN      NaN
25%     2075.250000       NaN        NaN   30.000000     NaN      NaN
50%     3199.500000       NaN        NaN   37.000000     NaN      NaN
75%     5092.750000       NaN        NaN   45.000000     NaN      NaN
max     6209.000000       NaN        NaN   59.000000     NaN      NaN

          caste study_level occupation empl_st_before_lckdwn  ...  anxiety T2  \
count       994         994        994                   994  ...  994.000000
unique        3           8         43                     7  ...         NaN
top     General  Graduation    Service    Full-time salaried  ...         NaN
freq        498         403        155                   422  ...         NaN
mean        NaN         NaN        NaN                   NaN  ...    8.364185
std         NaN         NaN        NaN                   NaN  ...    8.715728
min         NaN         NaN        NaN                   NaN  ...    0.000000
25%         NaN         NaN        NaN                   NaN  ...    0.000000
50%         NaN         NaN        NaN                   NaN  ...    6.000000
75%         NaN         NaN        NaN                   NaN  ...   14.000000
max         NaN         NaN        NaN                   NaN  ...   38.000000

        anxiety_level T2  relative_anx   stress T1 stress_level T1  \
count                994           994  994.000000             994
unique                 5             3         NaN               5
top               Normal          Same         NaN          Normal
freq                 556           578         NaN             644
mean                 NaN           NaN   12.257545             NaN
std                  NaN           NaN   10.500375             NaN
min                  NaN           NaN    0.000000             NaN
25%                  NaN           NaN    4.000000             NaN
50%                  NaN           NaN   10.000000             NaN
75%                  NaN           NaN   20.000000             NaN
max                  NaN           NaN   42.000000             NaN

         stress T2 stress_level T2 relative_stress dass21_raw T1  zdass21 T1
count   994.000000             994             994    994.000000  994.000000
unique         NaN               5               3           NaN         NaN
top            NaN          Normal            Same           NaN         NaN
freq           NaN             724             681           NaN         NaN
mean     10.670020             NaN             NaN     11.496982    0.031169
std       9.303529             NaN             NaN      9.960875    0.976359
min       0.000000             NaN             NaN      0.000000   -1.094910
25%       4.000000             NaN             NaN      3.333333   -0.769021
50%       8.000000             NaN             NaN      8.000000   -0.311127
75%      16.000000             NaN             NaN     20.000000    0.872319
max      40.000000             NaN             NaN     39.333332    2.764619

[11 rows x 95 columns]

In [ ]:
mh[mh['name'] == 'Srinivas']

     slno      name       city  age   sex religion caste       study_level  \
180  4052  Srinivas  Hyderabad   30  Male    Hindu   OBC        Graduation
188  4133  Srinivas  Hyderabad   37  Male    Hindu   OBC      Hr Secondary
528  4112  Srinivas  Hyderabad   45  Male    Hindu   OBC         Technical
610  4082  Srinivas  Hyderabad   33  Male    Hindu   OBC  Above graduation

    occupation empl_st_before_lckdwn  ... anxiety T2  anxiety_level T2  \
180    Service    Full-time salaried  ...          0            Normal
188    Service    Full-time salaried  ...          0            Normal
528    Service    Full-time salaried  ...          0            Normal
610   Business         Self-employed  ...          0            Normal

     relative_anx stress T1 stress_level T1 stress T2 stress_level T2  \
180          Same         4          Normal         0          Normal
188          Same         0          Normal         0          Normal
528          Same         0          Normal         0          Normal
610          Same         2          Normal         0          Normal

    relative_stress dass21_raw T1 zdass21 T1
180            Same      3.333333  -0.769696
188            Same      0.000000  -1.094910
528            Same      0.000000  -1.094910
610            Same      0.666667  -1.030023

[4 rows x 95 columns]

In [ ]:
mh.sample(10)

     slno              name       city  age     sex religion    caste  \
695  1221           Tsering  Bengaluru   49  Female    Hindu  General
945  1150             Ikram  Bengaluru   46    Male   Muslim  General
434  6173  AVINASH KULKARNI     Mumbai   58    Male    Hindu  General
796  1031         chidanand  Bengaluru   42    Male    Hindu      OBC
831  2190             Sunny    Chennai   51    Male   Others  General
111  1114         Lingaraju  Bengaluru   29    Male    Hindu    SC/ST
622  2169            Mukesh    Chennai   55    Male    Hindu    SC/ST
674  6045     PRITI KHETIYA     Mumbai   43  Female    Hindu  General
688  4184            Mahesh  Hyderabad   43    Male    Hindu      OBC
154  3026       Ansu Kumari      Delhi   30  Female    Hindu      OBC

          study_level     occupation      empl_st_before_lckdwn  ...  \
695            Middle  Self Employed              Self-employed  ...
945           Primary       business              Self-employed  ...
434        Graduation        SERVICE         Full-time salaried  ...
796        Graduation       business              Self-employed  ...
831         Secondary  self employed              Self-employed  ...
111            Middle        service         Full-time salaried  ...
622         Secondary  Self Employed              Self-employed  ...
674      Hr Secondary        SERVICE  Full-time variable income  ...
688        Graduation       Business              Self-employed  ...
154  Above graduation      Housewife                  Housewife  ...

    anxiety T2  anxiety_level T2   relative_anx stress T1 stress_level T1  \
695         28  Extremely severe           Same        24        Moderate
945         28  Extremely severe           Same        22        Moderate
434         18            Severe       Improved        16            Mild
796         22  Extremely severe  Deterioration        16            Mild
831         28  Extremely severe           Same        26          Severe
111         12          Moderate  Deterioration         0          Normal
622         24  Extremely severe           Same        30          Severe
674         10          Moderate           Same        10          Normal
688          0            Normal       Improved         4          Normal
154          0            Normal           Same        10          Normal

    stress T2 stress_level T2 relative_stress dass21_raw T1 zdass21 T1
695        22        Moderate            Same     26.666666   1.523720
945        32          Severe   Deterioration     26.000000   1.450426
434        14          Normal        Improved     19.333334   0.803475
796        22        Moderate   Deterioration     12.666667   0.144536
831        28          Severe            Same     28.666666   1.717032
111        14          Normal            Same      5.333334  -0.570001
622        26          Severe            Same     28.666666   1.715579
674         8          Normal            Same     10.666667  -0.047323
688         0          Normal            Same      8.000000  -0.308999
154         2          Normal            Same      6.666666  -0.446610

[10 rows x 95 columns]

In [ ]:
#Check duplicates
mh['slno'].duplicated().sum()

np.int64(0)

#### **Missing value dealing in column: `monthly_expenditure T1`**

In [ ]:
mh[mh['monthly_expenditure T1'].isna()]

     slno                  name     city  age     sex religion    caste  \
73   5197     ARCHANA DAS BASAK  Kolkata   37  Female    Hindu  General
465  5165  GITANJALI ROY MOITRA  Kolkata   49  Female    Hindu  General

          study_level occupation empl_st_before_lckdwn  ... anxiety T2  \
73          Technical    SERVICE    Full-time salaried  ...          0
465  Above graduation    TEACHER    Full-time salaried  ...          0

     anxiety_level T2  relative_anx stress T1 stress_level T1 stress T2  \
73             Normal          Same         4          Normal         0
465            Normal          Same         0          Normal         2

    stress_level T2 relative_stress dass21_raw T1 zdass21 T1
73           Normal            Same           2.0  -0.900923
465          Normal            Same           0.0  -1.094910

[2 rows x 95 columns]

* row[465] has no information in economic condition in T1 but T2.
* row[73] has no information in economic condition in T1 but in T2 they are filled with 0's.

 As theres no way of retrieving these missing informations, I'm removing these particular columns and else they would cause disruptions in our future analysis.

In [ ]:
mh1 = mh.copy()
mh1.drop([73,465], inplace=True)
mh1[mh1['monthly_expenditure T1'].isna()]
mh = mh1.copy()

In [ ]:
mh[mh['monthly_expenditure T1'].isna()]

Empty DataFrame
Columns: [slno, name, city, age, sex, religion, caste, study_level, occupation, empl_st_before_lckdwn, pymnt_st_main_erng_memb, family_mems, agd_memb_above60, mrd_and_spouse_living_together_or_not, residential_pattern, owned/rented, change_of_occ, change_of_occ_mainmember, married_unmarried, residence_change, family_economicaly_affected T1, family_economicaly_affected T2, monthly_expenditure T1, fmpce T1, mpce T1, monthly_expenditure T2, fmpce T2, mpce T2, education_of_children T1, education_of_children T2, leisure_time T1, leisure_time T2, covid_case T1, covid_case T2, fam_mem_suff_hyp-tens/bp/dbts/canc T1, fam_mem_suff_hyp-tens/bp/dbts/canc T2, finding_hard_to_wind_down_T1, finding_hard_to_wind_down_T2, dry_mouth T1, dry_mouth T2, not_experiencing_+ve_felling T1, not_experiencing_+ve_felling T2, breathing_difficulty T1, breathing_difficulty T2, difficulty_in_initiative_to_do_things T1, difficulty_in_initiative_to_do_things T2, overreaction_in_situations T1, overreaction_in_situations T2, experienced_trembling T1, experienced_trembling T2, felt_used_lotsof_nrvs_engy T1, felt_used_lotsof_nrvs_engy T2, panic_in_situations&make_fool_of_own T1, panic_in_situations&make_fool_of_own T2, felt_had_nothing_to_look_forward T1, felt_had_nothing_to_look_forward T2, getting_agitated T1, getting_agitated T2, difficulty_in_relax T1, difficulty_in_relax T2, felt_downhearted_and_blue T1, felt_downhearted_and_blue T2, intolerant_of_anything_gotin_my_way T1, intolerant_of_anything_gotin_my_way T2, felt_like_panicking T1, felt_like_panicking T2, unable_to_become_enthusiastic T1, unable_to_become_enthusiastic T2, felt_unworthy_as_a_person T1, felt_unworthy_as_a_person T2, felt_being_touchy T1, felt_being_touchy T2, abnormal_heart_rate T1, abnormal_heart_rate T2, felt_scared_without_reason T1, felt_scared_without_reason T2, felt_life_is_meaningless T1, felt_life_is_meaningless T2, depression T1, depression_level T1, depression T2, depression_level T2, relative_dep, anxiety T1, anxiety_level T1, anxiety T2, anxiety_level T2, relative_anx, stress T1, stress_level T1, stress T2, stress_level T2, relative_stress, dass21_raw T1, zdass21 T1]
Index: []

[0 rows x 95 columns]

#### **Missing value dealing in column: `monthly_expenditure T2`**

In [ ]:
mh[mh['monthly_expenditure T2'].isna()]

     slno               name     city  age     sex religion    caste  \
86   5067            PIU DAS  Kolkata   37  Female    Hindu  General
529  5072  BULA BHATTACHARYA  Kolkata   48  Female    Hindu  General

          study_level occupation empl_st_before_lckdwn  ... anxiety T2  \
86   Above graduation    SERVICE    Full-time salaried  ...          0
529      Hr Secondary  HOUSEWIFE             Housewife  ...          8

     anxiety_level T2  relative_anx stress T1 stress_level T1 stress T2  \
86             Normal          Same         4          Normal        10
529              Mild      Improved        14          Normal        18

    stress_level T2 relative_stress dass21_raw T1 zdass21 T1
86           Normal            Same      5.333334  -0.571454
529            Mild   Deterioration     17.333334   0.601756

[2 rows x 95 columns]

* row[86] has no information in economic condition in T1 but T2.
* row[529] has no information in economic condition in T1 but in T2 they are filled with 0's.

 As theres no way of retrieving these missing informations, I'm removing these particular columns and else they would cause disruptions in our future analysis.

In [ ]:
mh2 = mh.copy()
mh2.drop([86,529], inplace=True)
mh2[mh2['monthly_expenditure T2'].isna()]
mh = mh2.copy()

In [ ]:
mh[mh['monthly_expenditure T1'].isna()]

Empty DataFrame
Columns: [slno, name, city, age, sex, religion, caste, study_level, occupation, empl_st_before_lckdwn, pymnt_st_main_erng_memb, family_mems, agd_memb_above60, mrd_and_spouse_living_together_or_not, residential_pattern, owned/rented, change_of_occ, change_of_occ_mainmember, married_unmarried, residence_change, family_economicaly_affected T1, family_economicaly_affected T2, monthly_expenditure T1, fmpce T1, mpce T1, monthly_expenditure T2, fmpce T2, mpce T2, education_of_children T1, education_of_children T2, leisure_time T1, leisure_time T2, covid_case T1, covid_case T2, fam_mem_suff_hyp-tens/bp/dbts/canc T1, fam_mem_suff_hyp-tens/bp/dbts/canc T2, finding_hard_to_wind_down_T1, finding_hard_to_wind_down_T2, dry_mouth T1, dry_mouth T2, not_experiencing_+ve_felling T1, not_experiencing_+ve_felling T2, breathing_difficulty T1, breathing_difficulty T2, difficulty_in_initiative_to_do_things T1, difficulty_in_initiative_to_do_things T2, overreaction_in_situations T1, overreaction_in_situations T2, experienced_trembling T1, experienced_trembling T2, felt_used_lotsof_nrvs_engy T1, felt_used_lotsof_nrvs_engy T2, panic_in_situations&make_fool_of_own T1, panic_in_situations&make_fool_of_own T2, felt_had_nothing_to_look_forward T1, felt_had_nothing_to_look_forward T2, getting_agitated T1, getting_agitated T2, difficulty_in_relax T1, difficulty_in_relax T2, felt_downhearted_and_blue T1, felt_downhearted_and_blue T2, intolerant_of_anything_gotin_my_way T1, intolerant_of_anything_gotin_my_way T2, felt_like_panicking T1, felt_like_panicking T2, unable_to_become_enthusiastic T1, unable_to_become_enthusiastic T2, felt_unworthy_as_a_person T1, felt_unworthy_as_a_person T2, felt_being_touchy T1, felt_being_touchy T2, abnormal_heart_rate T1, abnormal_heart_rate T2, felt_scared_without_reason T1, felt_scared_without_reason T2, felt_life_is_meaningless T1, felt_life_is_meaningless T2, depression T1, depression_level T1, depression T2, depression_level T2, relative_dep, anxiety T1, anxiety_level T1, anxiety T2, anxiety_level T2, relative_anx, stress T1, stress_level T1, stress T2, stress_level T2, relative_stress, dass21_raw T1, zdass21 T1]
Index: []

[0 rows x 95 columns]

In [ ]:
mh[mh['monthly_expenditure T2'].isna()]

Empty DataFrame
Columns: [slno, name, city, age, sex, religion, caste, study_level, occupation, empl_st_before_lckdwn, pymnt_st_main_erng_memb, family_mems, agd_memb_above60, mrd_and_spouse_living_together_or_not, residential_pattern, owned/rented, change_of_occ, change_of_occ_mainmember, married_unmarried, residence_change, family_economicaly_affected T1, family_economicaly_affected T2, monthly_expenditure T1, fmpce T1, mpce T1, monthly_expenditure T2, fmpce T2, mpce T2, education_of_children T1, education_of_children T2, leisure_time T1, leisure_time T2, covid_case T1, covid_case T2, fam_mem_suff_hyp-tens/bp/dbts/canc T1, fam_mem_suff_hyp-tens/bp/dbts/canc T2, finding_hard_to_wind_down_T1, finding_hard_to_wind_down_T2, dry_mouth T1, dry_mouth T2, not_experiencing_+ve_felling T1, not_experiencing_+ve_felling T2, breathing_difficulty T1, breathing_difficulty T2, difficulty_in_initiative_to_do_things T1, difficulty_in_initiative_to_do_things T2, overreaction_in_situations T1, overreaction_in_situations T2, experienced_trembling T1, experienced_trembling T2, felt_used_lotsof_nrvs_engy T1, felt_used_lotsof_nrvs_engy T2, panic_in_situations&make_fool_of_own T1, panic_in_situations&make_fool_of_own T2, felt_had_nothing_to_look_forward T1, felt_had_nothing_to_look_forward T2, getting_agitated T1, getting_agitated T2, difficulty_in_relax T1, difficulty_in_relax T2, felt_downhearted_and_blue T1, felt_downhearted_and_blue T2, intolerant_of_anything_gotin_my_way T1, intolerant_of_anything_gotin_my_way T2, felt_like_panicking T1, felt_like_panicking T2, unable_to_become_enthusiastic T1, unable_to_become_enthusiastic T2, felt_unworthy_as_a_person T1, felt_unworthy_as_a_person T2, felt_being_touchy T1, felt_being_touchy T2, abnormal_heart_rate T1, abnormal_heart_rate T2, felt_scared_without_reason T1, felt_scared_without_reason T2, felt_life_is_meaningless T1, felt_life_is_meaningless T2, depression T1, depression_level T1, depression T2, depression_level T2, relative_dep, anxiety T1, anxiety_level T1, anxiety T2, anxiety_level T2, relative_anx, stress T1, stress_level T1, stress T2, stress_level T2, relative_stress, dass21_raw T1, zdass21 T1]
Index: []

[0 rows x 95 columns]

####
* **Missing and inconsistent values removed from columns `monthly_expenditure T1` and `monthly_expenditure T2`**

In [ ]:
mh[mh['fmpce T1'].isna()]
mh[mh['fmpce T2'].isna()]
mh[mh['mpce T1'].isna()]
mh[mh['mpce T2'].isna()]

Empty DataFrame
Columns: [slno, name, city, age, sex, religion, caste, study_level, occupation, empl_st_before_lckdwn, pymnt_st_main_erng_memb, family_mems, agd_memb_above60, mrd_and_spouse_living_together_or_not, residential_pattern, owned/rented, change_of_occ, change_of_occ_mainmember, married_unmarried, residence_change, family_economicaly_affected T1, family_economicaly_affected T2, monthly_expenditure T1, fmpce T1, mpce T1, monthly_expenditure T2, fmpce T2, mpce T2, education_of_children T1, education_of_children T2, leisure_time T1, leisure_time T2, covid_case T1, covid_case T2, fam_mem_suff_hyp-tens/bp/dbts/canc T1, fam_mem_suff_hyp-tens/bp/dbts/canc T2, finding_hard_to_wind_down_T1, finding_hard_to_wind_down_T2, dry_mouth T1, dry_mouth T2, not_experiencing_+ve_felling T1, not_experiencing_+ve_felling T2, breathing_difficulty T1, breathing_difficulty T2, difficulty_in_initiative_to_do_things T1, difficulty_in_initiative_to_do_things T2, overreaction_in_situations T1, overreaction_in_situations T2, experienced_trembling T1, experienced_trembling T2, felt_used_lotsof_nrvs_engy T1, felt_used_lotsof_nrvs_engy T2, panic_in_situations&make_fool_of_own T1, panic_in_situations&make_fool_of_own T2, felt_had_nothing_to_look_forward T1, felt_had_nothing_to_look_forward T2, getting_agitated T1, getting_agitated T2, difficulty_in_relax T1, difficulty_in_relax T2, felt_downhearted_and_blue T1, felt_downhearted_and_blue T2, intolerant_of_anything_gotin_my_way T1, intolerant_of_anything_gotin_my_way T2, felt_like_panicking T1, felt_like_panicking T2, unable_to_become_enthusiastic T1, unable_to_become_enthusiastic T2, felt_unworthy_as_a_person T1, felt_unworthy_as_a_person T2, felt_being_touchy T1, felt_being_touchy T2, abnormal_heart_rate T1, abnormal_heart_rate T2, felt_scared_without_reason T1, felt_scared_without_reason T2, felt_life_is_meaningless T1, felt_life_is_meaningless T2, depression T1, depression_level T1, depression T2, depression_level T2, relative_dep, anxiety T1, anxiety_level T1, anxiety T2, anxiety_level T2, relative_anx, stress T1, stress_level T1, stress T2, stress_level T2, relative_stress, dass21_raw T1, zdass21 T1]
Index: []

[0 rows x 95 columns]

####
* **We dealt with the Missing inconsistent values of `fmpce T1/T2` and `mpce T1/T2` through previous operations**

In [ ]:
mh.describe(include='all')

               slno      name       city         age     sex religion  \
count    990.000000       990        990  990.000000     990      990
unique          NaN       910          6         NaN       2        3
top             NaN  Srinivas  Bengaluru         NaN  Female    Hindu
freq            NaN         4        182         NaN     513      898
mean    3534.983838       NaN        NaN   38.131313     NaN      NaN
std     1724.341279       NaN        NaN    9.093655     NaN      NaN
min     1001.000000       NaN        NaN   21.000000     NaN      NaN
25%     2074.250000       NaN        NaN   30.000000     NaN      NaN
50%     3197.500000       NaN        NaN   36.000000     NaN      NaN
75%     5091.750000       NaN        NaN   45.000000     NaN      NaN
max     6209.000000       NaN        NaN   59.000000     NaN      NaN

          caste study_level occupation empl_st_before_lckdwn  ...  anxiety T2  \
count       990         990        990                   990  ...  990.000000
unique        3           8         42                     7  ...         NaN
top     General  Graduation    Service    Full-time salaried  ...         NaN
freq        494         403        155                   419  ...         NaN
mean        NaN         NaN        NaN                   NaN  ...    8.389899
std         NaN         NaN        NaN                   NaN  ...    8.721132
min         NaN         NaN        NaN                   NaN  ...    0.000000
25%         NaN         NaN        NaN                   NaN  ...    0.000000
50%         NaN         NaN        NaN                   NaN  ...    6.000000
75%         NaN         NaN        NaN                   NaN  ...   14.000000
max         NaN         NaN        NaN                   NaN  ...   38.000000

        anxiety_level T2  relative_anx   stress T1 stress_level T1  \
count                990           990  990.000000             990
unique                 5             3         NaN               5
top               Normal          Same         NaN          Normal
freq                 553           575         NaN             640
mean                 NaN           NaN   12.284848             NaN
std                  NaN           NaN   10.507625             NaN
min                  NaN           NaN    0.000000             NaN
25%                  NaN           NaN    4.000000             NaN
50%                  NaN           NaN   10.000000             NaN
75%                  NaN           NaN   20.000000             NaN
max                  NaN           NaN   42.000000             NaN

         stress T2 stress_level T2 relative_stress dass21_raw T1  zdass21 T1
count   990.000000             990             990    990.000000  990.000000
unique         NaN               5               3           NaN         NaN
top            NaN          Normal            Same           NaN         NaN
freq           NaN             721             678           NaN         NaN
mean     10.682828             NaN             NaN     11.518519    0.033281
std       9.309117             NaN             NaN      9.966050    0.976868
min       0.000000             NaN             NaN      0.000000   -1.094910
25%       4.000000             NaN             NaN      3.333333   -0.769021
50%       8.000000             NaN             NaN      8.000000   -0.310452
75%      16.000000             NaN             NaN     20.500000    0.904365
max      40.000000             NaN             NaN     39.333332    2.764619

[11 rows x 95 columns]

####
 **There are still missing values in `education_of_children T1
/T2`**
* For the moment we will keep those and treat the missing entries as NaN

**Possible Solution:**

As economic status is directly related to education of child, so if we observe that a certain family's economic condition from phase T1 to T2,
* got better, we could assign `not affected` in T2
* if it got worse and the change is small and the family is in economically well enough, we could assign `not affected` in T2
* if it got worse and the change cannot be considered as small although not a drastic change either we could assign `somewhat affected` in T2
* if it got worse and the change is drastic, we could assign `severely affected` in T2

If economic status of a certain family in phase T1 is,
* better, we could assign `not affected`
* somewhat better, we could assign `somewhat affected`
* not well enogh, we could assign `severely affected`

In [ ]:
# Missing values in 'education_of_children T1'

mh['education_of_children T1'].isna().sum()

np.int64(201)

In [ ]:
# Missing values in 'education_of_children T2'

mh['education_of_children T2'].isna().sum()

np.int64(146)

In [ ]:
# Missing values in both 'education_of_children T1/t2'

no_children_edu = mh[(mh['education_of_children T1'].isna()) & (mh['education_of_children T2'].isna())]

# Could be possible that they have no child or child death due to covid or they genuinely did not provided information

     slno                       name     city  age     sex religion    caste  \
1    5058                  TITAS ROY  Kolkata   28    Male    Hindu  General
11   5042             MOUMI BANERJEE  Kolkata   29  Female    Hindu  General
21   6159          PRATHNA CHOUDHARY   Mumbai   26  Female    Hindu  General
23   5117      SOUMALYA MUKHOPADHYAY  Kolkata   25    Male    Hindu  General
27   2191  Refused to share the name  Chennai   30    Male    Hindu    SC/ST
..    ...                        ...      ...  ...     ...      ...      ...
989  5064         SAHEB BHATTACHARYA  Kolkata   34    Male    Hindu  General
990  3021                Rohit Kumar    Delhi   28    Male    Hindu      OBC
991  3031               Megha Kumari    Delhi   31  Female    Hindu      OBC
992  5029                   MIRA DAS  Kolkata   49  Female    Hindu  General
993  3009                Mehul Kumar    Delhi   32    Male    Hindu    SC/ST

          study_level       occupation empl_st_before_lckdwn  ... anxiety T2  \
1    Above graduation  RESEARCH ANALYS    Full-time salaried  ...          0
11   Above graduation          SERVICE    Full-time salaried  ...          0
21         Graduation          SERVICE    Full-time salaried  ...          0
23         Graduation          SERVICE    Full-time salaried  ...         10
27          Technical          service    Full-time salaried  ...          8
..                ...              ...                   ...  ...        ...
989        Graduation    SELF EMPLOYED         Self-employed  ...          0
990  Above graduation          Service    Full-time salaried  ...          0
991  Above graduation          Service    Full-time salaried  ...          0
992            Middle        HOUSEWIFE             Housewife  ...          4
993        Graduation          Service    Full-time salaried  ...         10

     anxiety_level T2   relative_anx stress T1 stress_level T1 stress T2  \
1              Normal           Same        10          Normal         6
11             Normal       Improved         6          Normal         2
21             Normal           Same        30          Severe         8
23           Moderate  Deterioration        16            Mild        12
27               Mild       Improved        10          Normal         8
..                ...            ...       ...             ...       ...
989            Normal           Same         6          Normal        10
990            Normal           Same         6          Normal        10
991            Normal           Same        14          Normal         6
992            Normal           Same         6          Normal        10
993          Moderate  Deterioration         0          Normal        10

    stress_level T2 relative_stress dass21_raw T1 zdass21 T1
1            Normal            Same      5.333334  -0.577837
11           Normal            Same      6.000000  -0.503764
21           Normal        Improved     16.666666   0.526126
23           Normal        Improved     11.333333   0.002099
27           Normal            Same     10.666667  -0.050125
..              ...             ...           ...        ...
989          Normal            Same      3.333333  -0.769021
990          Normal            Same      3.333333  -0.771824
991          Normal            Same      8.000000  -0.319638
992          Normal            Same      9.333333  -0.191109
993          Normal            Same      0.666667  -1.030697

[115 rows x 95 columns]

###**Missing values in `monthly_expenditure T2`:**

In [ ]:
b = (mh['monthly_expenditure T1'] <= mh['monthly_expenditure T2']) & ((mh['education_of_children T1'].notna())) & (mh['education_of_children T2'].isna()) & (mh['mrd_and_spouse_living_together_or_not']!='Unmarried')
mh[b]

     slno            name       city  age     sex religion    caste  \
35   3173      Ashu Gupta      Delhi   28  Female    Hindu    SC/ST
241  3079    Rajesh Sahoo      Delhi   36    Male    Hindu      OBC
262  4074    Rama Krishna  Hyderabad   45    Male    Hindu      OBC
336  3154     Lovely Kaur      Delhi   33  Female    Hindu  General
505  3070     Rahul Kumar      Delhi   34    Male    Hindu    SC/ST
530  5061  SOMENATH MITRA    Kolkata   56    Male    Hindu  General
712  3027   Santosh Kumar      Delhi   28    Male    Hindu  General
739  5018   BABUSONA SAHA    Kolkata   31    Male    Hindu  General

          study_level       occupation empl_st_before_lckdwn  ... anxiety T2  \
35       Hr Secondary        Housewife             Housewife  ...          0
241        Graduation          Service    Full-time salaried  ...          0
262  Above graduation          Service    Full-time salaried  ...          2
336        Graduation        Housewife             Housewife  ...          0
505      Hr Secondary          Service    Full-time salaried  ...          0
530  Above graduation        PROFESSOR    Full-time salaried  ...          0
712      Hr Secondary        Bussiness         Self-employed  ...          2
739            Middle  DRIVER SALARIED    Full-time salaried  ...          2

     anxiety_level T2  relative_anx stress T1 stress_level T1 stress T2  \
35             Normal          Same         4          Normal         0
241            Normal      Improved        18            Mild         0
262            Normal          Same         0          Normal         0
336            Normal          Same         4          Normal         4
505            Normal          Same        28          Severe        12
530            Normal          Same         6          Normal         0
712            Normal          Same         8          Normal         4
739            Normal          Same         0          Normal         0

    stress_level T2 relative_stress dass21_raw T1 zdass21 T1
35           Normal            Same      1.333333  -0.965136
241          Normal        Improved     13.333333   0.209423
262          Normal            Same      0.000000  -1.094910
336          Normal            Same      1.333333  -0.965136
505          Normal        Improved     16.666666   0.525451
530          Normal            Same      4.666666  -0.643399
712          Normal            Same      4.000000  -0.706937
739          Normal            Same      0.000000  -1.094910

[8 rows x 95 columns]

#####
Respondents whose `monthly_expenditure T2` was greater than or equal to T1 and who were married, but had missing values in `education_of_children T2` despite having valid responses in `education_of_children T1`, were assigned the category `somewhat affecte` for `education_of_children T2`.
* This imputation was performed using a mode-based approach, as`somewhat affecte` was the most frequently occurring category in the dataset. Given the relative stability or increase in household expenditure across phases, this category was considered the most statistically and contextually appropriate representation for the missing responses.

In [ ]:
mh.loc[b, 'education_of_children T2'] = mh.loc[b, 'education_of_children T2'].fillna('Somewhat affected')
mh[b]

     slno            name       city  age     sex religion    caste  \
35   3173      Ashu Gupta      Delhi   28  Female    Hindu    SC/ST
241  3079    Rajesh Sahoo      Delhi   36    Male    Hindu      OBC
262  4074    Rama Krishna  Hyderabad   45    Male    Hindu      OBC
336  3154     Lovely Kaur      Delhi   33  Female    Hindu  General
505  3070     Rahul Kumar      Delhi   34    Male    Hindu    SC/ST
530  5061  SOMENATH MITRA    Kolkata   56    Male    Hindu  General
712  3027   Santosh Kumar      Delhi   28    Male    Hindu  General
739  5018   BABUSONA SAHA    Kolkata   31    Male    Hindu  General

          study_level       occupation empl_st_before_lckdwn  ... anxiety T2  \
35       Hr Secondary        Housewife             Housewife  ...          0
241        Graduation          Service    Full-time salaried  ...          0
262  Above graduation          Service    Full-time salaried  ...          2
336        Graduation        Housewife             Housewife  ...          0
505      Hr Secondary          Service    Full-time salaried  ...          0
530  Above graduation        PROFESSOR    Full-time salaried  ...          0
712      Hr Secondary        Bussiness         Self-employed  ...          2
739            Middle  DRIVER SALARIED    Full-time salaried  ...          2

     anxiety_level T2  relative_anx stress T1 stress_level T1 stress T2  \
35             Normal          Same         4          Normal         0
241            Normal      Improved        18            Mild         0
262            Normal          Same         0          Normal         0
336            Normal          Same         4          Normal         4
505            Normal          Same        28          Severe        12
530            Normal          Same         6          Normal         0
712            Normal          Same         8          Normal         4
739            Normal          Same         0          Normal         0

    stress_level T2 relative_stress dass21_raw T1 zdass21 T1
35           Normal            Same      1.333333  -0.965136
241          Normal        Improved     13.333333   0.209423
262          Normal            Same      0.000000  -1.094910
336          Normal            Same      1.333333  -0.965136
505          Normal        Improved     16.666666   0.525451
530          Normal            Same      4.666666  -0.643399
712          Normal            Same      4.000000  -0.706937
739          Normal            Same      0.000000  -1.094910

[8 rows x 95 columns]

In [ ]:
mh['education_of_children T2'].describe()

count                   852
unique                    3
top       Severely affected
freq                    443
Name: education_of_children T2, dtype: object

#####
* Non-Null value count in mh['education_of_children T2'] went to **852**

###**Missing values in `monthly_expenditure T1`:**

In [ ]:
a = ((mh['education_of_children T1'].isna()) & (mh['education_of_children T2'].notna()) & (mh['mrd_and_spouse_living_together_or_not']!='Unmarried'))
a1 = (a & (abs(mh['monthly_expenditure T1'] - mh['monthly_expenditure T2'])<= 2000))
mh[a1]

     slno             name       city  age     sex religion    caste  \
3    3014     Anunay Kumar      Delhi   35    Male    Hindu  General
7    4168         Bharathi  Hyderabad   30  Female    Hindu      OBC
97   4120         Gouthami  Hyderabad   26  Female    Hindu      OBC
154  3026      Ansu Kumari      Delhi   30  Female    Hindu      OBC
198  4199       Jalaluddin  Hyderabad   30    Male   Muslim  General
213  4104         Pranitha  Hyderabad   26  Female    Hindu  General
305  4023  M.Sridhar Reddy  Hyderabad   31    Male    Hindu  General
378  4095      Renuka Devi  Hyderabad   32  Female    Hindu      OBC
396  2112             Rani    Chennai   55  Female    Hindu    SC/ST
414  3004     Pranay Kumar      Delhi   31    Male    Hindu  General
540  5168        JONNY DAS    Kolkata   33    Male    Hindu  General
568  5001        RITA PAUL    Kolkata   55  Female    Hindu  General
604  1024       Prabavathi  Bengaluru   31  Female    Hindu    SC/ST
728  4187        Tejaswini  Hyderabad   26  Female    Hindu      OBC
730  4083         V.Harish  Hyderabad   29    Male    Hindu      OBC
884  3201   Gurvinder Kaur      Delhi   40  Female   Others  General
954  6022     ARPITA YADAV     Mumbai   45  Female    Hindu      OBC

          study_level  occupation empl_st_before_lckdwn  ... anxiety T2  \
3          Graduation     Service    Full-time salaried  ...          4
7          Graduation  House Wife             Housewife  ...          0
97         Graduation  House Wife             Housewife  ...          0
154  Above graduation   Housewife             Housewife  ...          0
198  Above graduation     Service    Full-time salaried  ...          0
213        Graduation  House Wife             Housewife  ...          2
305         Technical     Service    Full-time salaried  ...          0
378  Above graduation  House Wife             Housewife  ...          4
396            Middle   Housewife             Housewife  ...         12
414        Graduation     Service    Full-time salaried  ...          0
540        Graduation     SERVICE    Full-time salaried  ...          0
568        Graduation   HOUSEWIFE             Housewife  ...          0
604         Technical   housewife             Housewife  ...         14
728        Graduation  House Wife             Housewife  ...          0
730         Technical    Business         Self-employed  ...          0
884        Graduation   Housewife             Housewife  ...          0
954           Primary   HOUSEWIFE             Housewife  ...         12

     anxiety_level T2   relative_anx stress T1 stress_level T1 stress T2  \
3              Normal           Same         6          Normal        12
7              Normal           Same         4          Normal         8
97             Normal           Same         2          Normal         6
154            Normal           Same        10          Normal         2
198            Normal           Same         0          Normal         0
213            Normal           Same         4          Normal         4
305            Normal       Improved        10          Normal         0
378            Normal           Same         0          Normal         6
396          Moderate  Deterioration        16            Mild        12
414            Normal           Same         6          Normal         0
540            Normal           Same         0          Normal         0
568            Normal           Same         4          Normal         6
604          Moderate  Deterioration         2          Normal        16
728            Normal           Same         2          Normal         0
730            Normal           Same         0          Normal         2
884            Normal           Same         2          Normal         4
954          Moderate       Improved        10          Normal         6

    stress_level T2 relative_stress dass21_raw T1 zdass21 T1
3            Normal            Same      3.333333  -0.769021
7            Normal            Same      2.666667  -0.831106
97           Normal            Same      2.666667  -0.828978
154          Normal            Same      6.666666  -0.446610
198          Normal            Same      0.000000  -1.094910
213          Normal            Same      1.333333  -0.965136
305          Normal            Same      8.000000  -0.309778
378          Normal            Same      1.333333  -0.960880
396          Normal        Improved     12.000000   0.077521
414          Normal            Same      3.333333  -0.769021
540          Normal            Same      0.000000  -1.094910
568          Normal            Same      6.000000  -0.507241
604            Mild   Deterioration      1.333333  -0.963008
728          Normal            Same      2.000000  -0.895993
730          Normal            Same      0.000000  -1.094910
884          Normal            Same      2.000000  -0.898795
954          Normal            Same     14.000000   0.279344

[17 rows x 95 columns]

####
For respondents (married) with missing values in `education_of_children T1` but available values in `education_of_children T2`, the T1 values were imputed using the corresponding T2 values when the difference in monthly_expenditure between T1 and T2 was less than ₹2000
* This approach is based on the assumption that households whose monthly expenditure did not change substantially across the two phases, were likely to  remain in a almost similar economic status over a span of one year, and therefore were expected to maintain similar educational expenditure patterns for children.

In [ ]:
mh.loc[a1, 'education_of_children T1'] = mh.loc[a1, 'education_of_children T2']
mh[a1]

     slno             name       city  age     sex religion    caste  \
3    3014     Anunay Kumar      Delhi   35    Male    Hindu  General
7    4168         Bharathi  Hyderabad   30  Female    Hindu      OBC
97   4120         Gouthami  Hyderabad   26  Female    Hindu      OBC
154  3026      Ansu Kumari      Delhi   30  Female    Hindu      OBC
198  4199       Jalaluddin  Hyderabad   30    Male   Muslim  General
213  4104         Pranitha  Hyderabad   26  Female    Hindu  General
305  4023  M.Sridhar Reddy  Hyderabad   31    Male    Hindu  General
378  4095      Renuka Devi  Hyderabad   32  Female    Hindu      OBC
396  2112             Rani    Chennai   55  Female    Hindu    SC/ST
414  3004     Pranay Kumar      Delhi   31    Male    Hindu  General
540  5168        JONNY DAS    Kolkata   33    Male    Hindu  General
568  5001        RITA PAUL    Kolkata   55  Female    Hindu  General
604  1024       Prabavathi  Bengaluru   31  Female    Hindu    SC/ST
728  4187        Tejaswini  Hyderabad   26  Female    Hindu      OBC
730  4083         V.Harish  Hyderabad   29    Male    Hindu      OBC
884  3201   Gurvinder Kaur      Delhi   40  Female   Others  General
954  6022     ARPITA YADAV     Mumbai   45  Female    Hindu      OBC

          study_level  occupation empl_st_before_lckdwn  ... anxiety T2  \
3          Graduation     Service    Full-time salaried  ...          4
7          Graduation  House Wife             Housewife  ...          0
97         Graduation  House Wife             Housewife  ...          0
154  Above graduation   Housewife             Housewife  ...          0
198  Above graduation     Service    Full-time salaried  ...          0
213        Graduation  House Wife             Housewife  ...          2
305         Technical     Service    Full-time salaried  ...          0
378  Above graduation  House Wife             Housewife  ...          4
396            Middle   Housewife             Housewife  ...         12
414        Graduation     Service    Full-time salaried  ...          0
540        Graduation     SERVICE    Full-time salaried  ...          0
568        Graduation   HOUSEWIFE             Housewife  ...          0
604         Technical   housewife             Housewife  ...         14
728        Graduation  House Wife             Housewife  ...          0
730         Technical    Business         Self-employed  ...          0
884        Graduation   Housewife             Housewife  ...          0
954           Primary   HOUSEWIFE             Housewife  ...         12

     anxiety_level T2   relative_anx stress T1 stress_level T1 stress T2  \
3              Normal           Same         6          Normal        12
7              Normal           Same         4          Normal         8
97             Normal           Same         2          Normal         6
154            Normal           Same        10          Normal         2
198            Normal           Same         0          Normal         0
213            Normal           Same         4          Normal         4
305            Normal       Improved        10          Normal         0
378            Normal           Same         0          Normal         6
396          Moderate  Deterioration        16            Mild        12
414            Normal           Same         6          Normal         0
540            Normal           Same         0          Normal         0
568            Normal           Same         4          Normal         6
604          Moderate  Deterioration         2          Normal        16
728            Normal           Same         2          Normal         0
730            Normal           Same         0          Normal         2
884            Normal           Same         2          Normal         4
954          Moderate       Improved        10          Normal         6

    stress_level T2 relative_stress dass21_raw T1 zdass21 T1
3            Normal            Same      3.333333  -0.769021
7            Normal            Same      2.666667  -0.831106
97           Normal            Same      2.666667  -0.828978
154          Normal            Same      6.666666  -0.446610
198          Normal            Same      0.000000  -1.094910
213          Normal            Same      1.333333  -0.965136
305          Normal            Same      8.000000  -0.309778
378          Normal            Same      1.333333  -0.960880
396          Normal        Improved     12.000000   0.077521
414          Normal            Same      3.333333  -0.769021
540          Normal            Same      0.000000  -1.094910
568          Normal            Same      6.000000  -0.507241
604            Mild   Deterioration      1.333333  -0.963008
728          Normal            Same      2.000000  -0.895993
730          Normal            Same      0.000000  -1.094910
884          Normal            Same      2.000000  -0.898795
954          Normal            Same     14.000000   0.279344

[17 rows x 95 columns]

In [ ]:
mh['education_of_children T1'].describe()

count                   806
unique                    3
top       Severely affected
freq                    459
Name: education_of_children T1, dtype: object

#####
* Non-Null value count in mh['education_of_children T1'] went to **806**

In [ ]:
a = ((mh['education_of_children T1'].isna()) & (mh['education_of_children T2'].notna()) & (mh['mrd_and_spouse_living_together_or_not']!='Unmarried'))
a2 = (a & ((mh['monthly_expenditure T1'] - mh['monthly_expenditure T2']) >= 0) & ((mh['education_of_children T2']=='Not affected') | (mh['education_of_children T2']=='Somewhat affected')))
mh[a2]

     slno                  name       city  age     sex religion    caste  \
39   6104        PARESH CHABRIA     Mumbai   32    Male    Hindu  General
50   6175  DHANANJAY MAHADEVKAR     Mumbai   58    Male    Hindu  General
214  3170                  Ruby      Delhi   34  Female    Hindu  General
355  3003            Amita Karn      Delhi   27  Female    Hindu  General
422  6161          DISHA PANDEY     Mumbai   36  Female    Hindu  General
448  3037          Rupam Ranjan      Delhi   28  Female    Hindu      OBC
489  5030           INDIRA SAHA    Kolkata   46  Female    Hindu  General
499  6155          MAYURI GUPTA     Mumbai   36  Female    Hindu  General
544  6001            MEDHA MULE     Mumbai   54  Female    Hindu  General
563  6167            SAPNA MOTA     Mumbai   52  Female    Hindu  General
603  6074          ARCHANA POLO     Mumbai   29  Female    Hindu    SC/ST
639  3198                  Asha      Delhi   52  Female    Hindu  General
642  6163       SATESTINA GOMES     Mumbai   42  Female   Others  General
652  6187          ANWAR SHAIKH     Mumbai   54    Male   Muslim  General
681  3136       Sweety Sachdeva      Delhi   43  Female    Hindu  General
700  6024          JANTRI GUPTA     Mumbai   59  Female    Hindu  General
707  6153         NIKITA SAWANT     Mumbai   55  Female    Hindu  General
766  6189    MOINUDDIN GOLANDAZ     Mumbai   56    Male   Muslim  General
804  6178          RAFIK SHAIKH     Mumbai   55    Male   Muslim  General
828  1025             Sridhar m  Bengaluru   45    Male    Hindu      OBC
871  6180            ANWAR SHAH     Mumbai   51    Male   Muslim  General
943  3153                 Nilam      Delhi   50  Female    Hindu  General

      study_level     occupation empl_st_before_lckdwn  ... anxiety T2  \
39     Graduation        SERVICE    Full-time salaried  ...          4
50     Graduation        SERVICE    Full-time salaried  ...          4
214    Graduation      Housewife             Housewife  ...          2
355    Graduation      Housewife             Housewife  ...          0
422  Hr Secondary        SERVICE    Full-time salaried  ...          8
448    Graduation      Housewife             Housewife  ...          0
489  Hr Secondary      LIC AGENT         Self-employed  ...          0
499  Hr Secondary        SERVICE    Full-time salaried  ...         16
544     Secondary      HOUSEWIFE             Housewife  ...         12
563    Graduation        SERVICE    Full-time salaried  ...         10
603     Secondary      HOUSEWIFE             Housewife  ...          2
639    Graduation      Housewife             Housewife  ...          2
642    Graduation      HOUSEWIFE         Self-employed  ...          6
652     Secondary       BUSINESS         Self-employed  ...          0
681    Graduation      Housewife             Housewife  ...          0
700        Middle     UNEMPLOYED            Unemployed  ...         16
707  Hr Secondary       BUSINESS         Self-employed  ...         10
766       Primary       BUSINESS         Self-employed  ...         10
804     Secondary       BUSINESS         Self-employed  ...          6
828    Graduation  self employed         Self-employed  ...         26
871     Secondary       BUSINESS         Self-employed  ...          6
943    Graduation      Housewife             Housewife  ...          0

     anxiety_level T2   relative_anx stress T1   stress_level T1 stress T2  \
39             Normal       Improved        24          Moderate        12
50             Normal       Improved        24          Moderate         4
214            Normal           Same         0            Normal         6
355            Normal           Same         6            Normal         4
422              Mild       Improved        40  Extremely severe        16
448            Normal           Same        10            Normal         0
489            Normal           Same         0            Normal         8
499            Severe       Improved        36  Extremely severe         6
544          Moderate  Deterioration         2            Normal        20
563          Moderate       Improved        22          Moderate         4
603            Normal       Improved        16              Mild         8
639            Normal           Same         4            Normal         4
642            Normal       Improved        22          Moderate         8
652            Normal       Improved        30            Severe         8
681            Normal           Same         8            Normal         4
700            Severe       Improved        22          Moderate         6
707          Moderate           Same        26            Severe         8
766          Moderate       Improved        24          Moderate        12
804            Normal       Improved        22          Moderate         4
828  Extremely severe  Deterioration         4            Normal        28
871            Normal       Improved        26            Severe        10
943            Normal           Same         6            Normal         0

    stress_level T2 relative_stress dass21_raw T1 zdass21 T1
39           Normal        Improved     18.666666   0.733554
50           Normal        Improved     20.666666   0.931796
214          Normal            Same      0.000000  -1.094910
355          Normal            Same      2.666667  -0.836036
422            Mild        Improved     34.666668   2.299667
448          Normal            Same      3.333333  -0.770474
489          Normal            Same      0.000000  -1.094910
499          Normal        Improved     24.666666   1.321119
544        Moderate   Deterioration      4.000000  -0.700553
563          Normal        Improved     21.333334   0.995334
603          Normal        Improved     20.000000   0.867687
639          Normal            Same      3.333333  -0.769696
642          Normal        Improved     19.333334   0.797092
652          Normal        Improved     24.000000   1.257685
681          Normal            Same      5.333334  -0.575709
700          Normal        Improved     20.666666   0.936726
707          Normal        Improved     18.666666   0.731426
766          Normal        Improved     24.000000   1.258463
804          Normal        Improved     24.000000   1.257788
828          Severe   Deterioration      6.000000  -0.504439
871          Normal        Improved     23.333334   1.186518
943          Normal            Same      3.333333  -0.771824

[22 rows x 95 columns]

####
For married respondents with missing values in `education_of_children T1` but available responses in `education_of_children T2`, the T1 values were imputed using the corresponding T2 values when monthly expenditure decreased from T1 to T2 and `education_of_children T2` was reported as `Somewhat affecte` or `Not affected`.
* This approach is based on the assumption that even if households experienced a decline in economic status over time, families that reported only moderate or no impact on children’s education in T2 were likely to have maintained similar educational expenditure patterns in the earlier phase T1.

In [ ]:
mh.loc[a2, 'education_of_children T1'] = mh.loc[a2, 'education_of_children T2']
mh[a2]

     slno                  name       city  age     sex religion    caste  \
39   6104        PARESH CHABRIA     Mumbai   32    Male    Hindu  General
50   6175  DHANANJAY MAHADEVKAR     Mumbai   58    Male    Hindu  General
214  3170                  Ruby      Delhi   34  Female    Hindu  General
355  3003            Amita Karn      Delhi   27  Female    Hindu  General
422  6161          DISHA PANDEY     Mumbai   36  Female    Hindu  General
448  3037          Rupam Ranjan      Delhi   28  Female    Hindu      OBC
489  5030           INDIRA SAHA    Kolkata   46  Female    Hindu  General
499  6155          MAYURI GUPTA     Mumbai   36  Female    Hindu  General
544  6001            MEDHA MULE     Mumbai   54  Female    Hindu  General
563  6167            SAPNA MOTA     Mumbai   52  Female    Hindu  General
603  6074          ARCHANA POLO     Mumbai   29  Female    Hindu    SC/ST
639  3198                  Asha      Delhi   52  Female    Hindu  General
642  6163       SATESTINA GOMES     Mumbai   42  Female   Others  General
652  6187          ANWAR SHAIKH     Mumbai   54    Male   Muslim  General
681  3136       Sweety Sachdeva      Delhi   43  Female    Hindu  General
700  6024          JANTRI GUPTA     Mumbai   59  Female    Hindu  General
707  6153         NIKITA SAWANT     Mumbai   55  Female    Hindu  General
766  6189    MOINUDDIN GOLANDAZ     Mumbai   56    Male   Muslim  General
804  6178          RAFIK SHAIKH     Mumbai   55    Male   Muslim  General
828  1025             Sridhar m  Bengaluru   45    Male    Hindu      OBC
871  6180            ANWAR SHAH     Mumbai   51    Male   Muslim  General
943  3153                 Nilam      Delhi   50  Female    Hindu  General

      study_level     occupation empl_st_before_lckdwn  ... anxiety T2  \
39     Graduation        SERVICE    Full-time salaried  ...          4
50     Graduation        SERVICE    Full-time salaried  ...          4
214    Graduation      Housewife             Housewife  ...          2
355    Graduation      Housewife             Housewife  ...          0
422  Hr Secondary        SERVICE    Full-time salaried  ...          8
448    Graduation      Housewife             Housewife  ...          0
489  Hr Secondary      LIC AGENT         Self-employed  ...          0
499  Hr Secondary        SERVICE    Full-time salaried  ...         16
544     Secondary      HOUSEWIFE             Housewife  ...         12
563    Graduation        SERVICE    Full-time salaried  ...         10
603     Secondary      HOUSEWIFE             Housewife  ...          2
639    Graduation      Housewife             Housewife  ...          2
642    Graduation      HOUSEWIFE         Self-employed  ...          6
652     Secondary       BUSINESS         Self-employed  ...          0
681    Graduation      Housewife             Housewife  ...          0
700        Middle     UNEMPLOYED            Unemployed  ...         16
707  Hr Secondary       BUSINESS         Self-employed  ...         10
766       Primary       BUSINESS         Self-employed  ...         10
804     Secondary       BUSINESS         Self-employed  ...          6
828    Graduation  self employed         Self-employed  ...         26
871     Secondary       BUSINESS         Self-employed  ...          6
943    Graduation      Housewife             Housewife  ...          0

     anxiety_level T2   relative_anx stress T1   stress_level T1 stress T2  \
39             Normal       Improved        24          Moderate        12
50             Normal       Improved        24          Moderate         4
214            Normal           Same         0            Normal         6
355            Normal           Same         6            Normal         4
422              Mild       Improved        40  Extremely severe        16
448            Normal           Same        10            Normal         0
489            Normal           Same         0            Normal         8
499            Severe       Improved        36  Extremely severe         6
544          Moderate  Deterioration         2            Normal        20
563          Moderate       Improved        22          Moderate         4
603            Normal       Improved        16              Mild         8
639            Normal           Same         4            Normal         4
642            Normal       Improved        22          Moderate         8
652            Normal       Improved        30            Severe         8
681            Normal           Same         8            Normal         4
700            Severe       Improved        22          Moderate         6
707          Moderate           Same        26            Severe         8
766          Moderate       Improved        24          Moderate        12
804            Normal       Improved        22          Moderate         4
828  Extremely severe  Deterioration         4            Normal        28
871            Normal       Improved        26            Severe        10
943            Normal           Same         6            Normal         0

    stress_level T2 relative_stress dass21_raw T1 zdass21 T1
39           Normal        Improved     18.666666   0.733554
50           Normal        Improved     20.666666   0.931796
214          Normal            Same      0.000000  -1.094910
355          Normal            Same      2.666667  -0.836036
422            Mild        Improved     34.666668   2.299667
448          Normal            Same      3.333333  -0.770474
489          Normal            Same      0.000000  -1.094910
499          Normal        Improved     24.666666   1.321119
544        Moderate   Deterioration      4.000000  -0.700553
563          Normal        Improved     21.333334   0.995334
603          Normal        Improved     20.000000   0.867687
639          Normal            Same      3.333333  -0.769696
642          Normal        Improved     19.333334   0.797092
652          Normal        Improved     24.000000   1.257685
681          Normal            Same      5.333334  -0.575709
700          Normal        Improved     20.666666   0.936726
707          Normal        Improved     18.666666   0.731426
766          Normal        Improved     24.000000   1.258463
804          Normal        Improved     24.000000   1.257788
828          Severe   Deterioration      6.000000  -0.504439
871          Normal        Improved     23.333334   1.186518
943          Normal            Same      3.333333  -0.771824

[22 rows x 95 columns]

In [ ]:
mh['education_of_children T1'].describe()

count                   828
unique                    3
top       Severely affected
freq                    459
Name: education_of_children T1, dtype: object

#####
* Non-Null value count in mh['education_of_children T1'] went to **828**

In [ ]:
mh['education_of_children T1'].isna().sum()

np.int64(162)

In [ ]:
mh['education_of_children T2'].isna().sum()

np.int64(138)

In [ ]:
c = ((mh['education_of_children T1'].notna()) & (mh['education_of_children T2'].isna()) & (mh['mrd_and_spouse_living_together_or_not']!='Unmarried'))
c1 = (c & ((mh['monthly_expenditure T1'] - mh['monthly_expenditure T2']) >= 5000) & ((mh['education_of_children T1']=='Severely affected') | (mh['education_of_children T1']=='Somewhat affected')))
mh[c1]

     slno            name       city  age     sex religion    caste  \
125  6131  CHANDAN NISHAB     Mumbai   29    Male    Hindu  General
137  6171     BABLU GUPTA     Mumbai   40    Male    Hindu  General
222  3132          Sakshi      Delhi   33  Female    Hindu  General
280  5051  MITA MUKHERJEE    Kolkata   51  Female    Hindu  General
659  5151       SUBOL DAS    Kolkata   55    Male    Hindu  General
758  6051    ANITA KUMARI     Mumbai   30  Female    Hindu  General
814  4179      Prem Kumar  Hyderabad   40    Male    Hindu      OBC
910  3183          Rupali      Delhi   30  Female    Hindu  General
983  4003          Ignesh  Hyderabad   59    Male    Hindu    SC/ST

          study_level occupation empl_st_before_lckdwn  ... anxiety T2  \
125        Graduation    SERVICE    Full-time salaried  ...         12
137      Hr Secondary    SERVICE    Full-time salaried  ...         12
222        Graduation  Housewife             Housewife  ...          0
280  Above graduation  HOUSEWIFE             Housewife  ...         12
659            Middle   BUSINESS         Self-employed  ...         12
758        Graduation  HOUSEWIFE             Housewife  ...          8
814        Graduation   Business         Self-employed  ...          0
910        Graduation  Housewife             Housewife  ...          6
983        Graduation    Retired               Retired  ...          0

     anxiety_level T2   relative_anx stress T1 stress_level T1 stress T2  \
125          Moderate       Improved        20        Moderate         6
137          Moderate  Deterioration         8          Normal        10
222            Normal           Same         2          Normal         2
280          Moderate  Deterioration         4          Normal        28
659          Moderate           Same        12          Normal        18
758              Mild           Same        10          Normal         6
814            Normal       Improved         8          Normal         0
910            Normal           Same         6          Normal         2
983            Normal       Improved        16            Mild         6

    stress_level T2 relative_stress dass21_raw T1 zdass21 T1
125          Normal        Improved     24.666666   1.318524
137          Normal            Same      7.333334  -0.380269
222          Normal            Same      2.666667  -0.834583
280          Severe   Deterioration      2.666667  -0.833908
659            Mild   Deterioration     12.666667   0.145989
758          Normal            Same      7.333334  -0.373990
814          Normal            Same      8.666667  -0.243437
910          Normal            Same      6.000000  -0.509369
983          Normal        Improved     11.333333   0.016111

[9 rows x 95 columns]

####**Missing values in `education_of_children T2`:**

#####
For married respondents, those who has missing responds in `education_of_children T2` but available response in `education_of_children T1`, the T2 values were imputed into corresponding T1 values when the families experienced a decline in `monthly expenditure` which is more than 5000, from T1 to T2.
* This approach is based on the assumption that the households whose children's education was already affected in T1 and faced a significant economic decline are likely to remain in the similar or worsening economic condition, thereby maintaining comparable educational impact status in T2.

In [ ]:
mh.loc[c1, 'education_of_children T2'] = mh.loc[c1, 'education_of_children T1']
mh[c1]

     slno            name       city  age     sex religion    caste  \
125  6131  CHANDAN NISHAB     Mumbai   29    Male    Hindu  General
137  6171     BABLU GUPTA     Mumbai   40    Male    Hindu  General
222  3132          Sakshi      Delhi   33  Female    Hindu  General
280  5051  MITA MUKHERJEE    Kolkata   51  Female    Hindu  General
659  5151       SUBOL DAS    Kolkata   55    Male    Hindu  General
758  6051    ANITA KUMARI     Mumbai   30  Female    Hindu  General
814  4179      Prem Kumar  Hyderabad   40    Male    Hindu      OBC
910  3183          Rupali      Delhi   30  Female    Hindu  General
983  4003          Ignesh  Hyderabad   59    Male    Hindu    SC/ST

          study_level occupation empl_st_before_lckdwn  ... anxiety T2  \
125        Graduation    SERVICE    Full-time salaried  ...         12
137      Hr Secondary    SERVICE    Full-time salaried  ...         12
222        Graduation  Housewife             Housewife  ...          0
280  Above graduation  HOUSEWIFE             Housewife  ...         12
659            Middle   BUSINESS         Self-employed  ...         12
758        Graduation  HOUSEWIFE             Housewife  ...          8
814        Graduation   Business         Self-employed  ...          0
910        Graduation  Housewife             Housewife  ...          6
983        Graduation    Retired               Retired  ...          0

     anxiety_level T2   relative_anx stress T1 stress_level T1 stress T2  \
125          Moderate       Improved        20        Moderate         6
137          Moderate  Deterioration         8          Normal        10
222            Normal           Same         2          Normal         2
280          Moderate  Deterioration         4          Normal        28
659          Moderate           Same        12          Normal        18
758              Mild           Same        10          Normal         6
814            Normal       Improved         8          Normal         0
910            Normal           Same         6          Normal         2
983            Normal       Improved        16            Mild         6

    stress_level T2 relative_stress dass21_raw T1 zdass21 T1
125          Normal        Improved     24.666666   1.318524
137          Normal            Same      7.333334  -0.380269
222          Normal            Same      2.666667  -0.834583
280          Severe   Deterioration      2.666667  -0.833908
659            Mild   Deterioration     12.666667   0.145989
758          Normal            Same      7.333334  -0.373990
814          Normal            Same      8.666667  -0.243437
910          Normal            Same      6.000000  -0.509369
983          Normal        Improved     11.333333   0.016111

[9 rows x 95 columns]

In [ ]:
mh['education_of_children T1'].isna().sum()

np.int64(162)

In [ ]:
mh['education_of_children T2'].isna().sum()

np.int64(129)

#### **Remaining Nan values in `education_of_children T1/T2`**
* The remaining NaN values cannot be filled with statistical approach, so we keep them as they are.
* Respondents whose both sections are blank, we are not dealing with them as there could be a possibility that they have no childrens, or they genuinely did not want to provide informations.

##### **There are entries which has (monthly_expenditure, fmpce, mpce)T1 == 0 but T2 != 0**

#####
* As these cases could potentially introduce inconsistencies into the analysis, and given that their frequency was relatively low compared to the overall dataset size, they were removed from the dataset.

In [ ]:
d1 = mh[mh['monthly_expenditure T1']==0]
mh.drop(d1.index , inplace=True)
d1

Empty DataFrame
Columns: [slno, name, city, age, sex, religion, caste, study_level, occupation, empl_st_before_lckdwn, pymnt_st_main_erng_memb, family_mems, agd_memb_above60, mrd_and_spouse_living_together_or_not, residential_pattern, owned/rented, change_of_occ, change_of_occ_mainmember, married_unmarried, residence_change, family_economicaly_affected T1, family_economicaly_affected T2, monthly_expenditure T1, fmpce T1, mpce T1, monthly_expenditure T2, fmpce T2, mpce T2, education_of_children T1, education_of_children T2, leisure_time T1, leisure_time T2, covid_case T1, covid_case T2, fam_mem_suff_hyp-tens/bp/dbts/canc T1, fam_mem_suff_hyp-tens/bp/dbts/canc T2, finding_hard_to_wind_down_T1, finding_hard_to_wind_down_T2, dry_mouth T1, dry_mouth T2, not_experiencing_+ve_felling T1, not_experiencing_+ve_felling T2, breathing_difficulty T1, breathing_difficulty T2, difficulty_in_initiative_to_do_things T1, difficulty_in_initiative_to_do_things T2, overreaction_in_situations T1, overreaction_in_situations T2, experienced_trembling T1, experienced_trembling T2, felt_used_lotsof_nrvs_engy T1, felt_used_lotsof_nrvs_engy T2, panic_in_situations&make_fool_of_own T1, panic_in_situations&make_fool_of_own T2, felt_had_nothing_to_look_forward T1, felt_had_nothing_to_look_forward T2, getting_agitated T1, getting_agitated T2, difficulty_in_relax T1, difficulty_in_relax T2, felt_downhearted_and_blue T1, felt_downhearted_and_blue T2, intolerant_of_anything_gotin_my_way T1, intolerant_of_anything_gotin_my_way T2, felt_like_panicking T1, felt_like_panicking T2, unable_to_become_enthusiastic T1, unable_to_become_enthusiastic T2, felt_unworthy_as_a_person T1, felt_unworthy_as_a_person T2, felt_being_touchy T1, felt_being_touchy T2, abnormal_heart_rate T1, abnormal_heart_rate T2, felt_scared_without_reason T1, felt_scared_without_reason T2, felt_life_is_meaningless T1, felt_life_is_meaningless T2, depression T1, depression_level T1, depression T2, depression_level T2, relative_dep, anxiety T1, anxiety_level T1, anxiety T2, anxiety_level T2, relative_anx, stress T1, stress_level T1, stress T2, stress_level T2, relative_stress, dass21_raw T1, zdass21 T1]
Index: []

[0 rows x 95 columns]

##### **There are entries which has (monthly_expenditure, fmpce, mpce)T2 == 0 but T1 != 0**

#####
* As these cases could potentially introduce inconsistencies into the analysis, and given that their frequency was relatively low compared to the overall dataset size, they were removed from the dataset.

In [ ]:
d2 = mh[mh['monthly_expenditure T2']==0]
mh.drop(d2.index , inplace=True)
d2

Empty DataFrame
Columns: [slno, name, city, age, sex, religion, caste, study_level, occupation, empl_st_before_lckdwn, pymnt_st_main_erng_memb, family_mems, agd_memb_above60, mrd_and_spouse_living_together_or_not, residential_pattern, owned/rented, change_of_occ, change_of_occ_mainmember, married_unmarried, residence_change, family_economicaly_affected T1, family_economicaly_affected T2, monthly_expenditure T1, fmpce T1, mpce T1, monthly_expenditure T2, fmpce T2, mpce T2, education_of_children T1, education_of_children T2, leisure_time T1, leisure_time T2, covid_case T1, covid_case T2, fam_mem_suff_hyp-tens/bp/dbts/canc T1, fam_mem_suff_hyp-tens/bp/dbts/canc T2, finding_hard_to_wind_down_T1, finding_hard_to_wind_down_T2, dry_mouth T1, dry_mouth T2, not_experiencing_+ve_felling T1, not_experiencing_+ve_felling T2, breathing_difficulty T1, breathing_difficulty T2, difficulty_in_initiative_to_do_things T1, difficulty_in_initiative_to_do_things T2, overreaction_in_situations T1, overreaction_in_situations T2, experienced_trembling T1, experienced_trembling T2, felt_used_lotsof_nrvs_engy T1, felt_used_lotsof_nrvs_engy T2, panic_in_situations&make_fool_of_own T1, panic_in_situations&make_fool_of_own T2, felt_had_nothing_to_look_forward T1, felt_had_nothing_to_look_forward T2, getting_agitated T1, getting_agitated T2, difficulty_in_relax T1, difficulty_in_relax T2, felt_downhearted_and_blue T1, felt_downhearted_and_blue T2, intolerant_of_anything_gotin_my_way T1, intolerant_of_anything_gotin_my_way T2, felt_like_panicking T1, felt_like_panicking T2, unable_to_become_enthusiastic T1, unable_to_become_enthusiastic T2, felt_unworthy_as_a_person T1, felt_unworthy_as_a_person T2, felt_being_touchy T1, felt_being_touchy T2, abnormal_heart_rate T1, abnormal_heart_rate T2, felt_scared_without_reason T1, felt_scared_without_reason T2, felt_life_is_meaningless T1, felt_life_is_meaningless T2, depression T1, depression_level T1, depression T2, depression_level T2, relative_dep, anxiety T1, anxiety_level T1, anxiety T2, anxiety_level T2, relative_anx, stress T1, stress_level T1, stress T2, stress_level T2, relative_stress, dass21_raw T1, zdass21 T1]
Index: []

[0 rows x 95 columns]

#####**In the 'occupation' column there are entries in uppercase consistency**

In [ ]:
mh['occupation'] = mh['occupation'].str.lower()
mh.head()

   slno             name     city  age     sex religion    caste  \
0  5056  SOUMYA DASGUPTA  Kolkata   46    Male    Hindu  General
1  5058        TITAS ROY  Kolkata   28    Male    Hindu  General
2  6036      MANOJ MOGRE   Mumbai   41    Male    Hindu  General
3  3014     Anunay Kumar    Delhi   35    Male    Hindu  General
4  6075      REKHA SAKYA   Mumbai   25  Female    Hindu    SC/ST

        study_level       occupation empl_st_before_lckdwn  ... anxiety T2  \
0        Graduation         advocate         Self-employed  ...         18
1  Above graduation  research analys    Full-time salaried  ...          0
2        Graduation          service    Full-time salaried  ...         16
3        Graduation          service    Full-time salaried  ...          4
4         Secondary          service    Part-time salaried  ...          4

   anxiety_level T2   relative_anx stress T1 stress_level T1 stress T2  \
0            Severe  Deterioration         8          Normal        20
1            Normal           Same        10          Normal         6
2            Severe  Deterioration         2          Normal        12
3            Normal           Same         6          Normal        12
4            Normal       Improved        16            Mild        10

  stress_level T2 relative_stress dass21_raw T1 zdass21 T1
0        Moderate   Deterioration     10.000000  -0.117815
1          Normal            Same      5.333334  -0.577837
2          Normal            Same      6.000000  -0.505113
3          Normal            Same      3.333333  -0.769021
4          Normal        Improved     24.666666   1.328384

[5 rows x 95 columns]

In [ ]:
aa = (mh['monthly_expenditure T1']/mh['fmpce T1'])
aa.describe()
# as theres no jump in percentiles, so input datas are correct.

count    978.000000
mean      73.504200
std        0.000002
min       73.504196
25%       73.504199
50%       73.504199
75%       73.504200
max       73.504206
dtype: float64

In [ ]:
T1_usd_value = (mh['monthly_expenditure T1']/mh['fmpce T1']).mean()
T1_usd_value  # 1USD equivalent in T1 phase

np.float64(73.50419959936725)

In [ ]:
mh = pd.read_csv('/content/adult mental health in indian metro cities 2001-2021 (reformed).csv')

In [ ]:
mh

     slno                name     city  age     sex religion    caste  \
0    5056     SOUMYA DASGUPTA  Kolkata   46    Male    Hindu  General
1    5058           TITAS ROY  Kolkata   28    Male    Hindu  General
2    6036         MANOJ MOGRE   Mumbai   41    Male    Hindu  General
3    3014        Anunay Kumar    Delhi   35    Male    Hindu  General
4    6075         REKHA SAKYA   Mumbai   25  Female    Hindu    SC/ST
..    ...                 ...      ...  ...     ...      ...      ...
973  3143         Lalita Koli    Delhi   55  Female    Hindu    SC/ST
974  5064  SAHEB BHATTACHARYA  Kolkata   34    Male    Hindu  General
975  3021         Rohit Kumar    Delhi   28    Male    Hindu      OBC
976  3031        Megha Kumari    Delhi   31  Female    Hindu      OBC
977  3009         Mehul Kumar    Delhi   32    Male    Hindu    SC/ST

          study_level       occupation empl_st_before_lckdwn  ... anxiety T2  \
0          Graduation         advocate         Self-employed  ...         18
1    Above graduation  research analys    Full-time salaried  ...          0
2          Graduation          service    Full-time salaried  ...         16
3          Graduation          service    Full-time salaried  ...          4
4           Secondary          service    Part-time salaried  ...          4
..                ...              ...                   ...  ...        ...
973      Hr Secondary        housewife             Housewife  ...         18
974        Graduation    self employed         Self-employed  ...          0
975  Above graduation          service    Full-time salaried  ...          0
976  Above graduation          service    Full-time salaried  ...          0
977        Graduation          service    Full-time salaried  ...         10

     anxiety_level T2   relative_anx stress T1 stress_level T1 stress T2  \
0              Severe  Deterioration         8          Normal        20
1              Normal           Same        10          Normal         6
2              Severe  Deterioration         2          Normal        12
3              Normal           Same         6          Normal        12
4              Normal       Improved        16            Mild        10
..                ...            ...       ...             ...       ...
973            Severe  Deterioration         8          Normal        14
974            Normal           Same         6          Normal        10
975            Normal           Same         6          Normal        10
976            Normal           Same        14          Normal         6
977          Moderate  Deterioration         0          Normal        10

    stress_level T2 relative_stress dass21_raw T1 zdass21 T1
0          Moderate   Deterioration     10.000000  -0.117815
1            Normal            Same      5.333334  -0.577837
2            Normal            Same      6.000000  -0.505113
3            Normal            Same      3.333333  -0.769021
4            Normal        Improved     24.666666   1.328384
..              ...             ...           ...        ...
973          Normal            Same      4.000000  -0.706937
974          Normal            Same      3.333333  -0.769021
975          Normal            Same      3.333333  -0.771824
976          Normal            Same      8.000000  -0.319638
977          Normal            Same      0.666667  -1.030697

[978 rows x 95 columns]

#####
**mpce: USD to INR**

In [ ]:
mh['mpce T1'] = np.round(mh['mpce T1']*T1_usd_value)
mh

     slno                name     city  age     sex religion    caste  \
0    5056     SOUMYA DASGUPTA  Kolkata   46    Male    Hindu  General
1    5058           TITAS ROY  Kolkata   28    Male    Hindu  General
2    6036         MANOJ MOGRE   Mumbai   41    Male    Hindu  General
3    3014        Anunay Kumar    Delhi   35    Male    Hindu  General
4    6075         REKHA SAKYA   Mumbai   25  Female    Hindu    SC/ST
..    ...                 ...      ...  ...     ...      ...      ...
973  3143         Lalita Koli    Delhi   55  Female    Hindu    SC/ST
974  5064  SAHEB BHATTACHARYA  Kolkata   34    Male    Hindu  General
975  3021         Rohit Kumar    Delhi   28    Male    Hindu      OBC
976  3031        Megha Kumari    Delhi   31  Female    Hindu      OBC
977  3009         Mehul Kumar    Delhi   32    Male    Hindu    SC/ST

          study_level       occupation empl_st_before_lckdwn  ... anxiety T2  \
0          Graduation         advocate         Self-employed  ...         18
1    Above graduation  research analys    Full-time salaried  ...          0
2          Graduation          service    Full-time salaried  ...         16
3          Graduation          service    Full-time salaried  ...          4
4           Secondary          service    Part-time salaried  ...          4
..                ...              ...                   ...  ...        ...
973      Hr Secondary        housewife             Housewife  ...         18
974        Graduation    self employed         Self-employed  ...          0
975  Above graduation          service    Full-time salaried  ...          0
976  Above graduation          service    Full-time salaried  ...          0
977        Graduation          service    Full-time salaried  ...         10

     anxiety_level T2   relative_anx stress T1 stress_level T1 stress T2  \
0              Severe  Deterioration         8          Normal        20
1              Normal           Same        10          Normal         6
2              Severe  Deterioration         2          Normal        12
3              Normal           Same         6          Normal        12
4              Normal       Improved        16            Mild        10
..                ...            ...       ...             ...       ...
973            Severe  Deterioration         8          Normal        14
974            Normal           Same         6          Normal        10
975            Normal           Same         6          Normal        10
976            Normal           Same        14          Normal         6
977          Moderate  Deterioration         0          Normal        10

    stress_level T2 relative_stress dass21_raw T1 zdass21 T1
0          Moderate   Deterioration     10.000000  -0.117815
1            Normal            Same      5.333334  -0.577837
2            Normal            Same      6.000000  -0.505113
3            Normal            Same      3.333333  -0.769021
4            Normal        Improved     24.666666   1.328384
..              ...             ...           ...        ...
973          Normal            Same      4.000000  -0.706937
974          Normal            Same      3.333333  -0.769021
975          Normal            Same      3.333333  -0.771824
976          Normal            Same      8.000000  -0.319638
977          Normal            Same      0.666667  -1.030697

[978 rows x 95 columns]

In [ ]:
bb = (mh['monthly_expenditure T2']/mh['fmpce T2'])
bb.describe()
# as theres no jump in percentiles, so input datas are correct.

count    978.000000
mean      78.407060
std        0.000002
min       78.407053
25%       78.407060
50%       78.407060
75%       78.407061
max       78.407065
dtype: float64

In [ ]:
T2_usd_value = (mh['monthly_expenditure T2']/mh['fmpce T2']).mean()
T2_usd_value  # 1USD equivalent in T2 phase

np.float64(78.40705987038487)

In [ ]:
mh['mpce T2'] = np.round(mh['mpce T2']*T2_usd_value)
mh

     slno                name     city  age     sex religion    caste  \
0    5056     SOUMYA DASGUPTA  Kolkata   46    Male    Hindu  General
1    5058           TITAS ROY  Kolkata   28    Male    Hindu  General
2    6036         MANOJ MOGRE   Mumbai   41    Male    Hindu  General
3    3014        Anunay Kumar    Delhi   35    Male    Hindu  General
4    6075         REKHA SAKYA   Mumbai   25  Female    Hindu    SC/ST
..    ...                 ...      ...  ...     ...      ...      ...
973  3143         Lalita Koli    Delhi   55  Female    Hindu    SC/ST
974  5064  SAHEB BHATTACHARYA  Kolkata   34    Male    Hindu  General
975  3021         Rohit Kumar    Delhi   28    Male    Hindu      OBC
976  3031        Megha Kumari    Delhi   31  Female    Hindu      OBC
977  3009         Mehul Kumar    Delhi   32    Male    Hindu    SC/ST

          study_level       occupation empl_st_before_lckdwn  ... anxiety T2  \
0          Graduation         advocate         Self-employed  ...         18
1    Above graduation  research analys    Full-time salaried  ...          0
2          Graduation          service    Full-time salaried  ...         16
3          Graduation          service    Full-time salaried  ...          4
4           Secondary          service    Part-time salaried  ...          4
..                ...              ...                   ...  ...        ...
973      Hr Secondary        housewife             Housewife  ...         18
974        Graduation    self employed         Self-employed  ...          0
975  Above graduation          service    Full-time salaried  ...          0
976  Above graduation          service    Full-time salaried  ...          0
977        Graduation          service    Full-time salaried  ...         10

     anxiety_level T2   relative_anx stress T1 stress_level T1 stress T2  \
0              Severe  Deterioration         8          Normal        20
1              Normal           Same        10          Normal         6
2              Severe  Deterioration         2          Normal        12
3              Normal           Same         6          Normal        12
4              Normal       Improved        16            Mild        10
..                ...            ...       ...             ...       ...
973            Severe  Deterioration         8          Normal        14
974            Normal           Same         6          Normal        10
975            Normal           Same         6          Normal        10
976            Normal           Same        14          Normal         6
977          Moderate  Deterioration         0          Normal        10

    stress_level T2 relative_stress dass21_raw T1 zdass21 T1
0          Moderate   Deterioration     10.000000  -0.117815
1            Normal            Same      5.333334  -0.577837
2            Normal            Same      6.000000  -0.505113
3            Normal            Same      3.333333  -0.769021
4            Normal        Improved     24.666666   1.328384
..              ...             ...           ...        ...
973          Normal            Same      4.000000  -0.706937
974          Normal            Same      3.333333  -0.769021
975          Normal            Same      3.333333  -0.771824
976          Normal            Same      8.000000  -0.319638
977          Normal            Same      0.666667  -1.030697

[978 rows x 95 columns]



**Value of rupees decreased:**
##### I made the conclusion by looking into the same figures in family income columns of both phase but difference in corresponding fmpce values.
As both surveys are performed in two different phases, and (fmpce T1) > (fmpce T2), which represnts that due to inflation and global economy, value of rupees decreased. We are saving both columns for future purpose.

* For now we will be working with rupee columns. For that case we need to convert the the mpce column from usd to rupees. We will be using the MPCE formula and total member counts in both phases.

#####
As monthly expenditure = fmpce, we are removing them

In [ ]:
mh = mh.drop(columns=['fmpce T1', 'fmpce T2'])

KeyError: "['fmpce T1', 'fmpce T2'] not found in axis"

In [ ]:
mh

     slno                name     city  age     sex religion    caste  \
0    5056     SOUMYA DASGUPTA  Kolkata   46    Male    Hindu  General
1    5058           TITAS ROY  Kolkata   28    Male    Hindu  General
2    6036         MANOJ MOGRE   Mumbai   41    Male    Hindu  General
3    3014        Anunay Kumar    Delhi   35    Male    Hindu  General
4    6075         REKHA SAKYA   Mumbai   25  Female    Hindu    SC/ST
..    ...                 ...      ...  ...     ...      ...      ...
973  3143         Lalita Koli    Delhi   55  Female    Hindu    SC/ST
974  5064  SAHEB BHATTACHARYA  Kolkata   34    Male    Hindu  General
975  3021         Rohit Kumar    Delhi   28    Male    Hindu      OBC
976  3031        Megha Kumari    Delhi   31  Female    Hindu      OBC
977  3009         Mehul Kumar    Delhi   32    Male    Hindu    SC/ST

          study_level       occupation empl_st_before_lckdwn  ... anxiety T2  \
0          Graduation         advocate         Self-employed  ...         18
1    Above graduation  research analys    Full-time salaried  ...          0
2          Graduation          service    Full-time salaried  ...         16
3          Graduation          service    Full-time salaried  ...          4
4           Secondary          service    Part-time salaried  ...          4
..                ...              ...                   ...  ...        ...
973      Hr Secondary        housewife             Housewife  ...         18
974        Graduation    self employed         Self-employed  ...          0
975  Above graduation          service    Full-time salaried  ...          0
976  Above graduation          service    Full-time salaried  ...          0
977        Graduation          service    Full-time salaried  ...         10

     anxiety_level T2   relative_anx stress T1 stress_level T1 stress T2  \
0              Severe  Deterioration         8          Normal        20
1              Normal           Same        10          Normal         6
2              Severe  Deterioration         2          Normal        12
3              Normal           Same         6          Normal        12
4              Normal       Improved        16            Mild        10
..                ...            ...       ...             ...       ...
973            Severe  Deterioration         8          Normal        14
974            Normal           Same         6          Normal        10
975            Normal           Same         6          Normal        10
976            Normal           Same        14          Normal         6
977          Moderate  Deterioration         0          Normal        10

    stress_level T2 relative_stress dass21_raw T1 zdass21 T1
0          Moderate   Deterioration     10.000000  -0.117815
1            Normal            Same      5.333334  -0.577837
2            Normal            Same      6.000000  -0.505113
3            Normal            Same      3.333333  -0.769021
4            Normal        Improved     24.666666   1.328384
..              ...             ...           ...        ...
973          Normal            Same      4.000000  -0.706937
974          Normal            Same      3.333333  -0.769021
975          Normal            Same      3.333333  -0.771824
976          Normal            Same      8.000000  -0.319638
977          Normal            Same      0.666667  -1.030697

[978 rows x 93 columns]

### **As of now we have dealt with almost all problems with our dataset, and it is ready for further analysis, which will be performed on a another notebook.**

In [ ]:
mh.to_csv('/content/adult mental health in indian metro cities 2001-2021 (reformed).csv', index=False)